<a href="https://colab.research.google.com/github/lakshmi-devagiri/Linear_Regression/blob/main/DECISON_TREE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DECISION TREE

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files
uploaded = files.upload()

Saving salaries.csv to salaries.csv


numpy is used for numerical computing.
Pandas is used fro Data Analysis and manipulation.


In [5]:
df=pd.read_csv('salaries.csv')
df

company                  job     degree  salary_more_then_100k
0       google      sales executive  bachelors                      0
1       google      sales executive    masters                      0
2       google     business manager  bachelors                      1
3       google     business manager    masters                      1
4       google  computer programmer  bachelors                      0
5       google  computer programmer    masters                      1
6   abc pharma      sales executive    masters                      0
7   abc pharma  computer programmer  bachelors                      0
8   abc pharma     business manager  bachelors                      0
9   abc pharma     business manager    masters                      1
10    facebook      sales executive  bachelors                      1
11    facebook      sales executive    masters                      1
12    facebook     business manager  bachelors                      1
13    facebook     business manager    masters                      1
14    facebook  computer programmer  bachelors                      1
15    facebook  computer programmer    masters                      1

In [6]:
#here, I am taking independent DataFrame varibles as input
inputs=df.drop('salary_more_then_100k',axis='columns')

In [7]:
inputs

company                  job     degree
0       google      sales executive  bachelors
1       google      sales executive    masters
2       google     business manager  bachelors
3       google     business manager    masters
4       google  computer programmer  bachelors
5       google  computer programmer    masters
6   abc pharma      sales executive    masters
7   abc pharma  computer programmer  bachelors
8   abc pharma     business manager  bachelors
9   abc pharma     business manager    masters
10    facebook      sales executive  bachelors
11    facebook      sales executive    masters
12    facebook     business manager  bachelors
13    facebook     business manager    masters
14    facebook  computer programmer  bachelors
15    facebook  computer programmer    masters

In [9]:
#Now we know that machine learning algorithms works on numbers not on strings.
#to convert one of the best method is Label-Encoder.
from sklearn.preprocessing import LabelEncoder


How Label Encoder works?
**Fit**: The Label Encoder first analyzes the unique categories in the categorical feature.
**Transform**: It then assigns a unique integer to each category, starting from 0.
**Mapping**: It creates a mapping between the original categories and the assigned integers




In [11]:
Label_jobs=LabelEncoder()
Label_company=LabelEncoder()
Label_degree=LabelEncoder()

In [12]:
inputs['jobs_n']=Label_jobs.fit_transform(inputs['company'])
inputs['company_n']=Label_company.fit_transform(inputs['job'])
inputs['degree_n']=Label_degree.fit_transform(inputs['degree'])


In [14]:
inputs

company                  job     degree  jobs_n  company_n  degree_n
0       google      sales executive  bachelors       2          2         0
1       google      sales executive    masters       2          2         1
2       google     business manager  bachelors       2          0         0
3       google     business manager    masters       2          0         1
4       google  computer programmer  bachelors       2          1         0
5       google  computer programmer    masters       2          1         1
6   abc pharma      sales executive    masters       0          2         1
7   abc pharma  computer programmer  bachelors       0          1         0
8   abc pharma     business manager  bachelors       0          0         0
9   abc pharma     business manager    masters       0          0         1
10    facebook      sales executive  bachelors       1          2         0
11    facebook      sales executive    masters       1          2         1
12    facebook     business manager  bachelors       1          0         0
13    facebook     business manager    masters       1          0         1
14    facebook  computer programmer  bachelors       1          1         0
15    facebook  computer programmer    masters       1          1         1

In [15]:
#Here I am creating new Dataframe and drop categorical data
inputs_n=inputs.drop(['company','job','degree'],axis='columns')
inputs_n

jobs_n  company_n  degree_n
0        2          2         0
1        2          2         1
2        2          0         0
3        2          0         1
4        2          1         0
5        2          1         1
6        0          2         1
7        0          1         0
8        0          0         0
9        0          0         1
10       1          2         0
11       1          2         1
12       1          0         0
13       1          0         1
14       1          1         0
15       1          1         1

In [16]:
from sklearn import tree

In [17]:
model=tree.DecisionTreeClassifier()

In [18]:
model.fit(inputs_n,df['salary_more_then_100k'])

DecisionTreeClassifier()

In [19]:
model.score(inputs_n,df['salary_more_then_100k'])

1.0

In [21]:
model.predict([[2,2,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

In [22]:
from google.colab import files
uploaded = files.upload()

Saving titanic.csv to titanic.csv


In [23]:
df=pd.read_csv('titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [28]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [ ]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [30]:
inputs=df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns')

In [31]:
inputs

Survived  Pclass     Sex   Age     Fare
0           0       3    male  22.0   7.2500
1           1       1  female  38.0  71.2833
2           1       3  female  26.0   7.9250
3           1       1  female  35.0  53.1000
4           0       3    male  35.0   8.0500
..        ...     ...     ...   ...      ...
886         0       2    male  27.0  13.0000
887         1       1  female  19.0  30.0000
888         0       3  female   NaN  23.4500
889         1       1    male  26.0  30.0000
890         0       3    male  32.0   7.7500

[891 rows x 5 columns]

In [32]:
from sklearn.preprocessing import LabelEncoder

In [34]:
le=LabelEncoder()

In [35]:
inputs['Sex']=le.fit_transform(inputs['Sex'])

In [36]:
inputs

Survived  Pclass  Sex   Age     Fare
0           0       3    1  22.0   7.2500
1           1       1    0  38.0  71.2833
2           1       3    0  26.0   7.9250
3           1       1    0  35.0  53.1000
4           0       3    1  35.0   8.0500
..        ...     ...  ...   ...      ...
886         0       2    1  27.0  13.0000
887         1       1    0  19.0  30.0000
888         0       3    0   NaN  23.4500
889         1       1    1  26.0  30.0000
890         0       3    1  32.0   7.7500

[891 rows x 5 columns]

In [37]:
from sklearn import tree
model=tree.DecisionTreeClassifier()

In [40]:
model.fit(inputs,df['Survived'])

DecisionTreeClassifier()

In [42]:
X=inputs
y=df['Survived']

In [43]:
from sklearn.model_selection import train_test_split
# Assuming your features are in 'X' and target variable is in 'y'
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [44]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

In [46]:
model.score(X_test,y_test)

1.0

In [48]:
inputs.head()

Survived  Pclass  Sex   Age     Fare
0         0       3    1  22.0   7.2500
1         1       1    0  38.0  71.2833
2         1       3    0  26.0   7.9250
3         1       1    0  35.0  53.1000
4         0       3    1  35.0   8.0500

In [49]:
model.predict([[0,3,1,35,53]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])

In [50]:
model.predict([[0,3,1,35,8.0500]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0])