<a href="https://colab.research.google.com/github/lakshmi-devagiri/Linear_Regression/blob/main/K_Fold_Cross_Validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**CROSS VALIDATION**
Evaluating Model Performance
For EXample:Classifying your emails is spam or not.
Here, First you train the model using whatever dataset you have once model is built to use different dataset for testing a model.
the model return the results back those results you can compare with truth to measure the accuracy of a model.
There are several ways you can perform this training steps

1.Use all Available data for training and test on same dataset.
Here, you are using 100.5 of Data for training the model and use the same dataset for testing.
2. Split available dataset into training and testing
For example In a datset out of 100% , 70% is for trainning and 30% is for testing.
This Technique works okay but not perfect.
3. K-fold Cross VAlidation
Example : Here, we are having 100 samples we divide them into folds so, here i am taking 5 folds each fold coints 20 sample and we can run multiple
iterations in the first iteration we use 2 to 5 as training data 1st fold is for testing the data note the score. similarly in 2nd iteration we use 1,3,4,5 as
trainig data and 2nd fold as testing data note the score.Similarly we can perform 5 iterations.After getting the 5 Scores take the average score.
This technique is very good  because you are giving variety of samples to your models.


In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
digits = load_digits()

In [15]:
# Splitting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.2)

In [16]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.95

In [17]:
SVM= SVC()
SVM.fit(X_train,y_train)
SVM.score(X_test,y_test)

0.9722222222222222

In [18]:
Random= RandomForestClassifier()
Random.fit(X_train,y_train)
Random.score(X_test,y_test)

0.9666666666666667

In the above 3 Algorithm the scores are changing everytime you execute.
Lets try k-fold and see how it works.....)

In [26]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=4)
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [27]:
#Here N_splits=3 , Splitting the data into 3 Iterations.


In [28]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9,10,11, 12 ,13,'apple','Mango','Grapes','Berry']):
    print(train_index,test_index)

[ 5  6  7  8  9 10 11 12 13 14 15 16] [0 1 2 3 4]
[ 0  1  2  3  4  9 10 11 12 13 14 15 16] [5 6 7 8]
[ 0  1  2  3  4  5  6  7  8 13 14 15 16] [ 9 10 11 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12] [13 14 15 16]


In [29]:
# StartifiedKFold= it helps to Classify the data Uniformly for better results.



In [30]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [32]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=4)

In [48]:
score_lr=[]
score_svm=[]
score_rf=[]

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
    score_lr.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    score_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=30),X_train,X_test,y_train,y_test))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [49]:
score_lr

[0.9355555555555556,
 0.9153674832962138,
 0.9510022271714922,
 0.9175946547884187]

In [50]:
score_rf


[0.9288888888888889,
 0.8953229398663697,
 0.9732739420935412,
 0.9198218262806236]

In [51]:
score_svm

[0.9644444444444444,
 0.9665924276169265,
 0.9821826280623608,
 0.9487750556792873]

In [ ]:
# instead of this code we can simply call cross validation method

In [52]:
from sklearn.model_selection import cross_val_score

In [54]:
# After call the Function first argument is your classifier, 2nd is X and 3rd is y
Logistic_Regression = cross_val_score(LogisticRegression(),digits.data,digits.target)


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [55]:
Logistic_Regression

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [56]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [58]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target)

array([0.93611111, 0.9       , 0.95264624, 0.97214485, 0.91922006])

In [59]:
cross_val_score(RandomForestClassifier(n_estimators=60),digits.data,digits.target)

array([0.91944444, 0.9       , 0.94707521, 0.96100279, 0.92200557])

This Cross validation method performs everything as the above for loop.